### ISSUE TITLE
Add ability to hook it into additional Test type tasks

### ISSUE THREAD

**Issue by acidbee** [radarsh/gradle-test-logger-plugin#10]
In some of the projects I work on, they split tests up with additional source sets to allow the task to incrementally run (i.e. unitTest, integrationTest, systemTest). It would be nice if I could hook this into these other test tasks.

`testlogger {
    testTasks ['test', 'integrationTest', 'systemTest']
}`

Or optionally, hook into any Test type task by default:
`tasks.withType(Test)`

**Comment by radarsh** [comment]
That's a great idea, thanks for suggesting. I will implement it for my next release.
