### ISSUE TITLE
Test time reporting under the threshold

### ISSUE THREAD

**Issue by joravasal** [radarsh/gradle-test-logger-plugin#101]
Hi,

Just a small idea to expand on the report of time the tests take to execute. It maybe could be possible to add another option other than slowThreshold, something along the lines of timeReportThreshold, to show the time of the tests from that time. Maybe in a different color (green? same color of the rest of the theme?), and use the slowThreshold just to be able to set a limit to what is acceptable.

Definitely not the most urgent or important change, but it would help in my case where I am trying to improve the time tests take, and I need to set the slowThreshold very low to see the times of most tests, which makes many go red and is more difficult to filter them at a glance.

Thanks for the effort on the plugin, it is very helpful.

**Comment by joravasal** [comment]
Hi, thanks for the prompt answer.

Yes, we are using it currently, but as I added this logging tool I thought it could be a nice addition. Again, it is really not a big deal, just something I thought could improve it :)

Feel free to close this ticket if you feel it doesn't add much to the logs.

**Comment by radarsh** [comment]
While I do see the value in your requirement, in the spirit of keeping the plugin logic simple and to avoid having conflicting configuration options I'm going to close this issue for now. We can accomplish what you're asking currently by setting `slowThreshold` to `0`. Example:

![image](https://user-images.githubusercontent.com/534512/48792948-750d2480-eced-11e8-969d-61064cb4aee3.png)
