### ISSUE TITLE
Prints corrupted json

### ISSUE THREAD

**Issue by yarulan** [radarsh/gradle-test-logger-plugin#104]
I log json in tests
```
System.out.println("ZZZZZZZZZZ: []");
```
In the console I get ` ZZZZZZZZZZ: [[]`.

**Comment by ifqthenp** [comment]
Hi there!

I noticed the same bug. For example, I have a Book object in a database, when I get the object from database and print it to the console when running tests with `gradle clean test`, the output is following:
`Book(id=10, title=The Book of Calculation, authors=[Author(id=8, firstName=Leonardo, lastName=Fibonacci)[], genres=[Genre(id=7, genreName=Mathematics)[], year=1202, comments=[[])`

Do you see these redundant empty square brackets in the output? When I remove the plugin from gradle config, then output works fine as usual.

**Comment by radarsh** [comment]
Thanks for reporting this. It must be due to the internal escaping of square brackets. Will have a look and let you know.

**Comment by ifqthenp** [comment]
Hi thank you for fixing this, but...

My output is still like this ```Book(id=1, title=Alice in Wonderland, authors=[Author(id=1, firstName=Lewis, lastName=Carrol)[], genres=[Genre(id=8, genreName=Children's Literature), Genre(id=2, genreName=Fantasy)[], year=1865, comments=[Comment(id=1, commentary=excellent)[])```

Do I need to update the version of the plugin?

**Comment by radarsh** [comment]
Hi, I haven't released a new version of the plugin. Once I do that you will be able to get the bug fix.
