### ISSUE TITLE
Add support for @Nested and @DisplayName

### ISSUE THREAD

**Issue by markjfisher** [radarsh/gradle-test-logger-plugin#106]
In tests that use the annotations `@Nested`, and `@DisplayName` it would be nice to honour these in the output.

Example output in IntelliJ:
![image](https://user-images.githubusercontent.com/1616940/51465696-59131700-1d60-11e9-8654-2d4b3c242cac.png)

Equivalent command line output with logger plugin:

![image](https://user-images.githubusercontent.com/1616940/51465750-7811a900-1d60-11e9-9572-e05f7470f3c3.png)

**Comment by markjfisher** [comment]
Example test setup:

```
class DefaultProductCatalogServiceTest {

    @Nested
    @DisplayName("By skuId AND productId")
    inner class VariantSummaryBySkuIdAndProductId {

        @Test
        fun `skuId matches no variants - empty list returned`() {
```

**Comment by radarsh** [comment]
It's doable. Gradle have added an internal property called `classDisplayName` as part of gradle/gradle#4424.

**Comment by radarsh** [comment]
The `classDisplayName` seems to break an existing functionality of Gradle. See https://github.com/gradle/gradle/pull/4425#issuecomment-462194330.

**Comment by giovannicandido** [comment]
Maybe releated. I would like to remove the full package names for a better read experience:

![image](https://user-images.githubusercontent.com/915892/53499205-a3399780-3a86-11e9-94b4-00e72107e7b8.png)

![image](https://user-images.githubusercontent.com/915892/53499218-a896e200-3a86-11e9-8b04-f29d4f26d5ce.png)

**Comment by radarsh** [comment]
@giovannicandido I'm in half minds about this. In fact if PR #109 is merged, it will automatically remove the full package names. However I consider this a breaking change as it changes the existing functionality.

**Comment by giovannicandido** [comment]
Nice work. I don't get why is a breaking change since in my understanding is just the console display which is affected, but maybe it is for the theming api?

Thanks.

**Comment by radarsh** [comment]
Yes, I mean it's a breaking change for the plugin in the sense that people who used to see fully qualified class names now suddenly won't. It won't break any builds or anything.

**Comment by radarsh** [comment]
I've handled this without introducing a breaking change. There is now a new option called `showSimpleNames` which you need to set to `true` to print the short names. Otherwise, the default behaviour will be to continue printing fully qualified class names bar instances where you have a `@DisplayName` annotation set.
