### ISSUE TITLE
Post suite summaries

### ISSUE THREAD

**Issue by acidbee** [radarsh/gradle-test-logger-plugin#11]
After completing a suite, a summary of some kind would be nice:
```
testlogger {
    showSummary true|false
}
```

The color in the current output is extremely useful for finding exactly which test failed while scrolling through, the summary could be an at-a-glance way to know what failed. I'm thinking the following pieces of information would be useful:

- Task status: SUCCESSFUL/FAILED/ERROR
- Number of tests
- Number passed
- Number skipped
- Number failed
- Number errored
- List of Package/Class/Method of failed and errored tests

I've been putting the following in our build.gradle files, but it would be nice not to have to repeat it everywhere:
```
afterSuite { desc, result ->
       if (!desc.parent) { // will match the outermost suite
           def output = "Results: ${result.resultType} (${result.testCount} tests, ${result.successfulTestCount} successes, ${result.failedTestCount} failures, ${result.skippedTestCount} skipped)"
           def startItem = '|  ', endItem = '  |'
           def repeatLength = startItem.length() + output.length() + endItem.length()
           println('\n' + ('-' * repeatLength) + '\n' + startItem + output + endItem + '\n' + ('-' * repeatLength))
       }
   }
```

**Comment by radarsh** [comment]
I had something like this in mind but seeing that Gradle already prints something very similar, I didn't implement it.

```
----------------------------------------------------------------------
|  Results: FAILURE (22 tests, 19 successes, 2 failures, 1 skipped)  |
----------------------------------------------------------------------

22 tests completed, 2 failed, 1 skipped
:test FAILED
```

**Comment by acidbee** [comment]
Hmm, must've missed that. That's not a surprise though, I'm still pretty new to Gradle. Guess I'll need to dig into the Gradle TestLoggingContainer class a little more.

I'm convinced I/we can come up with something btter, but certainly not something I would sweat over. I'll see if I can find some time to contribute a pull request.

**Comment by radarsh** [comment]
I just realised that Gradle only prints summary if there are failures. Probably a good idea to add an option to the test logger so that it prints a more detailed summary regardless of test failures.
