### ISSUE TITLE
Filtering standard stream doesn't seem to be working properly

### ISSUE THREAD

**Issue by rafiron** [radarsh/gradle-test-logger-plugin#114]
Hi,
I want my tests to enable logging only in case of failed test cases, but also I want to display the list of test cases being run (passed, skipped and failed). I read the documentation and used the following configuration:

```
testlogger {
        theme 'mocha'
        slowThreshold 800
        // to print stream only for failed test cases
        showStandardStreams true
        showPassedStandardStreams false
        showSkippedStandardStreams false
        showFailedStandardStreams true
    }
```

Now as per the configuration the logs being generated by the successful cases shouldn't come. My tests also try to cover some exception handling and when they go through the error handling phase, they log warnings and error messages, but the test cases successfully pass.

In such cases I can see that even though my cases are passing, the logs are coming when running tests; which I thought shouldn't be the case as per the configuration.

Am I missing something here and can anyone point me as to how I can achieve my use case ?

**Comment by radarsh** [comment]
Hi, when you set `showPassedStandardStreams` to `false`, it will only hide the stdout and stderr output from passing tests. The test run display (the line with the green tick against it) will still be shown. If you want to hide that too, you have to set `showPassed` to `false`.

Let me know if that is what you mean. Otherwise, I have misunderstood your requirement. Perhaps an example would help. I have created a [test branch](https://github.com/radarsh/gradle-test-logger-plugin-test/tree/bugfix/issue-114) to reproduce your scenario and it seems to be working as expected in that branch.

**Comment by rafiron** [comment]
I want the tests to be listed (the line with the tick), but don't want the logging to be done for the passing tests. Hence I don't want to set `showPassed` as `false`.
For the test cases which are passing, the logs are still getting printed, which I thought wouldn't be the case with this configuration and only the failed tests cases' logs will be printed.

I'll try to create a small test repo to try to replicate the problem.

**Comment by mikand13** [comment]
I can confirm this.

testlogger {
        theme = ThemeType.STANDARD_PARALLEL
        showPassed = true
        showSkipped = true
        showStandardStreams = true
        showPassedStandardStreams = false
        showSkippedStandardStreams = false
    }

I would expect this to show me the line with the green tick, but hide stdout logs for passing tests, but in fact it still outputs stdout for passed test.

**Comment by sescotti** [comment]
Hi, same problem here as described here, looks like the settings don't cause any effect. Furthermore, I tried setting `showSimpleNames` true and it seems it's not even a recognised property. Thanks!

**Comment by radarsh** [comment]
The change containing showSimpleNames is yet to be released.

**Comment by radarsh** [comment]
I have just released `1.7.0` but haven't done anything specific about this issue yet as for me it seems to still work. I will continue my analysis but meanwhile, if one of you could give `1.7.0` a spin to see if makes a difference, it would be really awesome.

**Comment by radarsh** [comment]
I think what you may be seeing is the test class level output produced by passing tests (JUnit 5's `@BeforeAll` and `@AfterAll`, JUnit 4's `@BeforeClass` and `@AfterClass` and Spock's `setupSpec` and `cleanupSpec`) which are currently not filtered if all tests in a given class are passing.

**Comment by patkovskyi** [comment]
It would be great to be able to filter `@BeforeClass` and `@AfterClass` output. 
With these settings I'm still seeing it on version 1.7.0: 
 
```
testlogger {
        showStandardStreams true
        showPassedStandardStreams false
        showSkippedStandardStreams false
        showFailedStandardStreams true
    }
```

**Comment by radarsh** [comment]
@patkovskyi that's the challenge I am facing. Currently, `@BeforeClass` output is logged _before_ any test outputs are produced and `@AfterClass` is logged _after_ the test output for the class in question. Given your configuration, say we have a scenario where we have 5 tests but none of them fails. By this time the `@BeforeClass` output would already have been logged. There is no way to know in advance whether all the tests in a given class are going to pass or not.

**Comment by radarsh** [comment]
Unfortunately due to the reason stated in my previous comment, this issue cannot be fixed. If you think the output you are seeing is not coming from `@BeforeClass` or `@AfterClass`, please raise another issue with sample output included.

**Comment by mikand13** [comment]
Just a comment, this includes spring context startup for spring boot tests effectively invalidating this option. Just FYI
