### ISSUE TITLE
Mocha on dark terminals

### ISSUE THREAD

**Issue by CSBaum** [radarsh/gradle-test-logger-plugin#115]
Hi,

I love the plugin and I do like the Mocha theme, but as I am running in a dark terminal the text is pretty much lost.  Is there a way to configure the colors? Or maybe have a mocha-light and a mocha-dark option?

Thanks in advance!

Sean

**Comment by radarsh** [comment]
Hi, thanks for using the plugin. The mocha theme tries to emulate the [Mocha JS's Spec reporter](https://mochajs.org/#spec) to a great extent and therefore uses similar colours as that of the JS version. For the same reason it wouldn't be right to modify the colours used. 

In this case, I suggest changing the terminal colour theme or adjust the meaning of ANSI grey (also called bright black). For instance, I use a Mac and in my iTerm2 preferences I can modify the highlighted colour to increase / decrease the brightness. Similar settings would exist for most platforms and terminals.

![image](https://user-images.githubusercontent.com/534512/54713562-d4b5f800-4b46-11e9-91d1-fbcba515b32b.png)
