### ISSUE TITLE
Not enough details about exception thrown by the test.

### ISSUE THREAD

**Issue by danbar74** [radarsh/gradle-test-logger-plugin#118]
When a test fails due to an exception being thrown, there's only the exception name/message being logged i.e.:
```console
SomeTests

    ✘ should ....

      java.lang.IllegalStateException: Failed to load ApplicationContext
```
What would be nice to get, is the cause - similar to what you get with standard gradle test logger + the following config:
```groovy
test {
    testLogging {
        exceptionFormat = TestExceptionFormat.FULL
    }
}
```
```console
SomeTest > should ... FAILED
    java.lang.IllegalStateException: Failed to load ApplicationContext

        Caused by:
        org.mockito.exceptions.base.MockitoException: 
        Cannot mock/spy class SomeClass
        Mockito cannot mock/spy because :
         - final class
```

**Comment by ivoanjo** [comment]
+1 I bumped into exactly the same issue, would be really great if you could get the full info on the exception easily.

**Comment by radarsh** [comment]
Fair enough. It's pretty straightforward to add this functionality. I will also make it "react" to the value of `testLogging.exceptionFormat`.

**Comment by radarsh** [comment]
PR #119 has been merged to develop. A sample output with `testlogger.showFullStackTraces` set to `true`:

![image](https://user-images.githubusercontent.com/534512/58593915-3344d400-8264-11e9-97fd-45774d50234e.png)

See README for more customisation options.

**Comment by EugenMayer** [comment]
Thank you for implementing this!

**Comment by ivoanjo** [comment]
👍 Thank you very very much, and have an awesome weekend! 😀
