### ISSUE TITLE
Add example image of summary to readme

### ISSUE THREAD

**Issue by mattdkerr** [radarsh/gradle-test-logger-plugin#126]
I really like the gifs being used for the readme.md but they don't really show you what the summary will look like- I think this would be helpful in understanding what other features the plugin has.

**Comment by radarsh** [comment]
There is already a link to the extremely thorough [screenshots](https://github.com/radarsh/gradle-test-logger-plugin/blob/develop/docs/SCREENSHOTS.md) page in the README.
