### ISSUE TITLE
theme is defaulted to plain even when maxForks is greater than 1

### ISSUE THREAD

**Issue by ataverasp** [radarsh/gradle-test-logger-plugin#139]
**Description**

When setting console = plain using the gradle command line and we have the test task with maxParallelForks > 1 an error is thrown with the following:

Parallel execution is not supported for theme type 'plain'. Must be one of 'plain-parallel', 'standard-parallel', 'mocha-parallel' 

**Versions**

- Test logger version: 2.0.0
- Gradle version: 5.6.2
- Java version: 1.8_0_222

**Type of test being run**

no tests at this point

**Test logger configuration**

```gradle
 testlogger {
        theme "${gradle.startParameter.consoleOutput == ConsoleOutput.Verbose ? 'mocha-parallel' : 'plain-parallel'}" //this is ignored because the Extension check if the consoleOutput is plain and it will ignore setting any other theme
        showExceptions true
        showStackTraces true
        showFullStackTraces false
        showCauses true
        slowThreshold 2000
        showSummary true
        showSimpleNames false
        showPassed true
        showSkipped true
        showFailed true
        showStandardStreams false
        showPassedStandardStreams true
        showSkippedStandardStreams true
        showFailedStandardStreams true
    }
```

**Comment by radarsh** [comment]
That's an interesting one. Maybe we should consider automatically switching to the `-parallel` version of the theme if `maxParallelForks` is greater than 1.

**Comment by nathan815** [comment]
@radarsh I think that'd be a good idea. No sense in throwing a "theme incompatible with parallel tests" error when it can be resolved by using the `-parallel` version.
