### ISSUE TITLE
Hierarchical tests do not output all levels

### ISSUE THREAD

**Issue by sksamuel** [radarsh/gradle-test-logger-plugin#141]
**Description**

Hierarchical tests do not output correctly.

**Versions**

- Test logger version: 2.0.0
- Gradle version: 6.0.1
- Java version: 11

**Type of test being run**

Kotest.io

**Test logger configuration**

Default.

**Screenshots**

These tests have multiple levels to them but only one level is output.

![image](https://user-images.githubusercontent.com/743706/72765440-0a39d080-3bb2-11ea-9b09-b0e6276038d3.png)

**Additional information**

This might not be an issue with this project. Gradle does the exact same thing. But there's been open bugs in gradle for 2 years+ so I'm hoping we can fix it here instead (plus the output of this plugin is far better).

**Comment by radarsh** [comment]
Thanks for a thorough bug report. Generally, I tend to rely on Gradle for test information in order to ensure good backward and forward compatibility. Let me see what's causing this in a bit more detail and advise.

**Comment by radarsh** [comment]
@sksamuel do you perhaps have the code that produced the above output? I am specifically interested in the test code demonstrating the hierarchical organisation as I am currently working on a feature to support nested test display.

See #146

**Comment by sksamuel** [comment]
You've got a bigger test suite than you could possibly ever need by just running `./gradlew check` on https://github.com/kotest/kotest :)

This is a Kotlin test framework built on top of Junit5 that uses arbitrarily nested scopes for testing. Many of the test cases for the framework itself use 2/3/4 levels of nesting.

**Comment by radarsh** [comment]
Not sure if it's pretty at this point, but I seem to be getting somewhere:

![image](https://user-images.githubusercontent.com/534512/75568534-5991dd00-5a4b-11ea-8398-0e0bfa059795.png)

**Comment by sksamuel** [comment]
Looks good. I'd probably have Test lined up on the left and indent after
that. Or maybe just have the word Test for top level entries.

**Comment by radarsh** [comment]
It looks odd in this case because there are tests being nested directly within other tests (unlike JUnit where classes containing tests are nested within tests). Let me see if I can detect this difference in the plugin and render the output correctly.

**Comment by sksamuel** [comment]
Junit has three states - container, container_test and test. In gradle
prior to 6.0, it would hang if you used container_test. So you might want
to handle container_test and container the same way.

**Comment by Hives** [comment]
are you going to display the names of the nested test classes, as well as the names of the tests?

**Comment by radarsh** [comment]
@Hives yes that's the plan. I've got most of it sorted now. Just need to work out a good design (UI) for displaying tests that are directly nested within other tests.

Also, for completeness, I'm going to verify that it works well for [each style of kotest](https://github.com/kotest/kotest/blob/master/doc/styles.md) and [spek framework](https://www.spekframework.org/specification/) for Kotlin based tests.

**Comment by Hives** [comment]
🙏
