### ISSUE TITLE
Indicate nested tests

### ISSUE THREAD

**Issue by Hives** [radarsh/gradle-test-logger-plugin#146]
Is it possible to indicate the nesting of `@Nested` tests by indenting them under their parent? 

Here's the current output we're getting:
![image](https://user-images.githubusercontent.com/847307/75031773-ec0c0c80-549e-11ea-969e-e34972efc22f.png)

The first nested block could be indented once, and the second nested block indented twice, and so on.

Here's what that looks like using the IntelliJ test runner - nested tests are clearly displayed as children of the parent level:
![image](https://user-images.githubusercontent.com/847307/75031748-e1517780-549e-11ea-8365-3afda562ed84.png)

Example tests used to produce this output:
```kotlin
@Nested
@DisplayName("Outer block")
internal class TestTest {

    @Test
    fun `Test in the outer block`() {
        assertThat(1 + 1).isEqualTo(2)
    }

    @Nested
    @DisplayName("First block")
    inner class FirstBlock {

        @Test
        fun `Test in the first nested block`() {
            assertThat(1 + 1).isEqualTo(2)
        }

        @Nested
        @DisplayName("Second block")
        inner class SecondBlock {

            @Test
            fun `Test in the second nested block`() {
                assertThat(1 + 1).isEqualTo(2)
            }
        }
    }
}
```

Thanks

**Comment by radarsh** [comment]
I've been doing some experimentation and it seems very much feasible.

**Comment by Hives** [comment]
hi @radarsh. did you ever get around to looking at this?

**Comment by radarsh** [comment]
Half way into this. One of the scenarios is turning out to be more complicated than I thought.
