### ISSUE TITLE
JetBrains IDEA prints the escape codes instead of switching colors

### ISSUE THREAD

**Issue by dsvensson** [radarsh/gradle-test-logger-plugin#148]
While this sounds like a limitation in IDEA, I do get colors in the console from slf4j/logback with `%highlight(%level)` log pattern, so some coloring should work. Is there any special setting that I lack?

**Comment by dsvensson** [comment]
Just noticed that it's working correctly when executing the gradle test task from the gradle view. For some reason it's broken when clicking "Run Tests" in project or editor.

Broken like:
```
[0K[1m  Test [22mshouldNotStuff1()[32m PASSED[m
[0K[1m  Test [22mshouldStuff2()[32m PASSED[m
[0K[1m  Test [22mshouldNotStuff3()[32m PASSED[m
```

...still as mentioned, slf4j/logback shows colors for logs correctly in both cases in the same output window.

**Comment by radarsh** [comment]
Yes I am aware of this. It was a conscious decision I had to make while fixing another bug. Let me see if I can achieve the best of both worlds.

**Comment by payne911** [comment]
Any updates on this?

**Comment by radarsh** [comment]
This is unrelated to the plugin. Just having something like the below in the build file and running in IntelliJ causes the output to be escaped.

```groovy
afterEvaluate {
    logger.lifecycle('\u001B[31mRED\u001B[0m')
}
```

However, as @dsvensson said, running the Gradle task from the Gradle panel in IntelliJ produces the colours.

Unfortunately, this is out of scope and there is nothing I can do here.
