### ISSUE TITLE
Auto Switch Theme based on --console value and --parallel

### ISSUE THREAD

**Issue by bellini-ea** [radarsh/gradle-test-logger-plugin#149]
**Description**

When using a commandline containing --parallel along with --console=plain on the commandline, test-logger fails with `Parallel execution is not supported for theme type 'plain'. Must be one of 'plain-parallel', 'standard-parallel', 'mocha-parallel'`.  

For example `gradlew test --console=plain --parallel`

- If I add code such as `testlogger { theme= ThemeType.PLAIN_PARALLEL }` I get the error
- If I add code such as `testlogger { theme= ThemeType.STANDARD_PARALLEL }` I still get the same error

Seems like as long as if have --console=plain it always fails but having --console=auto or rich works fine.  

It would be nice if auto switching themes was matched the console value provide or if this is bug then addressed.

**Additional information**
Using version 2.0.0 of the test-logger with Gradle 6.2.1

**Comment by radarsh** [comment]
This has already been implemented in #142. I just need to release a new version.

**Comment by bellini-ea** [comment]
Thanks.  Something does seem up with plain being used however.  Could be just  my setup though.

ETA on the release?

**Comment by radarsh** [comment]
I'll release it today.

**Comment by radarsh** [comment]
Published - [![Gradle plugin portal](https://img.shields.io/github/tag/radarsh/gradle-test-logger-plugin.svg?label=gradle+plugin+portal)](https://plugins.gradle.org/plugin/com.adarshr.test-logger)
