### ISSUE TITLE
Add filter: hide regular passing tests, show slow passing tests

### ISSUE THREAD

**Issue by C-Otto** [radarsh/gradle-test-logger-plugin#158]
**Description**

My project has several thousand (unit and integration) tests and I really don't want to see a line for each passing test.
However, there are a few slow tests, and the "slowThreshold" feature is extremely helpful - thank you!

To be able to identify the slow tests, I'd like to see the corresponding output, while the regular (fast) tests are not displayed.

**Additional information**

Current:
```
SomeTest testA PASSED
SomeTest testB PASSED
SomeTest testC PASSED
SomeTest testD PASSED (502ms)
```

Expected:
```
SomeTest testD PASSED (502ms)
```

**Comment by C-Otto** [comment]
Related to #159 (consider time spent in setUp).

**Comment by C-Otto** [comment]
Quirky workaround for one-shot scans of slow tests: `./gradlew test | grep "s)"`

**Comment by grimmjo** [comment]
Hi @radarsh,

what do you think about adding a parameter `showSlow`? It is true by default. 
This would be an easy extension to the existing code

**Comment by C-Otto** [comment]
Thanks a lot for the new release! This is how I use it in my project:

```
testlogger {
    theme 'standard-parallel'
    slowThreshold 1000
    showSimpleNames true
    showOnlySlow true
}
```
