### ISSUE TITLE
How does one remove the noise from output?

### ISSUE THREAD

**Issue by aedenj** [radarsh/gradle-test-logger-plugin#160]
I'm running `gradle test --continuous` in a console and like the format of the test output. I would like to fine tune it by removing the extra output produced by grade. For example this stuff

```
Virtual file system retained information about 108 files, 24 directories and 2 missing files since last build

> Task :clean
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses

> Task :test

```

and

```
BUILD SUCCESSFUL in 2s
4 actionable tasks: 4 executed
Received 5 file system events for current build
Virtual file system retains information about 108 files, 24 directories and 2 missing files till next build
```

What setting am I missing?

Thanks.

**Comment by radarsh** [comment]
You can just run Gradle using the `-q` (quiet) flag. Additionally, to see test logger output you will need to change the log level of test logger. Example:

```groovy
testlogger {
    theme 'mocha'
    logLevel 'QUIET'
}
```

Then run using `./gradlew test --continuous -q`

There is currently a bug which is preventing being able to specify the log level at command line. Once that is fixed, you will be able to simply do `./gradlew clean test --continuous -q -Dtestlogger.logLevel=quiet` without changing the configuration in your build file.

**Comment by ajameson-hbo** [comment]
That did it. Thanks.
