### ISSUE TITLE
Disable all output in CI environment

### ISSUE THREAD

**Issue by svenjacobs** [radarsh/gradle-test-logger-plugin#224]
It would be nice to provide a configuration option to disable any console output by the plugin, like if the plugin was not applied to the project at all. The reason for my request is that in a CI environment, all these outputs slow down the builds :( 

Of course I could conditionally add the plugin to the project based on certain system properties or so, however this would mean adjusting the project configuration at several places (e.g. where the plugin is applied and where it is configured). It would be much nicer if I just can do a

```
testlogger {
    silent = true
}
```

**Comment by radarsh** [comment]
You can already do that today by using the following configuration:

```groovy
testlogger {
    logLevel 'quiet'
}
```

https://github.com/radarsh/gradle-test-logger-plugin#change-log-level

**Comment by svenjacobs** [comment]
I tried `logLevel = LogLevel.QUIET` (Kotlin DSL) and I still see all the output :(

**Comment by radarsh** [comment]
Oh, maybe I haven't released it. I'll reopen it for now and look at it later.

**Comment by svenjacobs** [comment]
Well, the property is already there but it seems to have no effect as you describe. Thanks for looking into this.

**Comment by radarsh** [comment]
OK you can still do this using the current version. You need to set the log level for testlogger to be lower than the log level at which Gradle runs. The below are the Gradle log levels:

    DEBUG
    INFO
    LIFECYCLE
    WARN
    QUIET
    ERROR

By default Gradle uses LIFECYCLE. The plugin also logs at this level. So if you don't want any logs to appear you have two options:

1. Run Gradle using a level higher than LIFECYCLE on CI. This can be done by specifying either `--warn` or `--quiet` on the command line.
2. Run Gradle as normal but change testlogger configuration to use `logLevel 'info'` or `logLevel 'debug'`. You can also do this on the command line by passing a system property `testLogger.logLevel=info` or `testLogger.logLevel=debug`.

Hope that helps.

**Comment by radarsh** [comment]
Thanks. Fixed the typo :)
