### ISSUE TITLE
NoSuchMethodError: org.gradle.api.provider.Provider.forUseAtConfigurationTime()

### ISSUE THREAD

**Issue by zalizko** [radarsh/gradle-test-logger-plugin#225]
**Description**

java.lang.NoSuchMethodError: org/gradle/api/provider/Provider.forUseAtConfigurationTime()
at com.adarshr.gradle.testlogger.TestLoggerExtension.getTheme(TestLoggerExtension.groovy:71)

**Versions**

- Test logger version:  3.0.0
- Gradle version: 6.3
- Java version: openjdk version "1.8.0_292"

**Type of test being run**

JUnit 5 with useJUnitPlatform();

**Additional information**

With gradle 7.2 everything fine, 6.2 throw that exception.

**Comment by radarsh** [comment]
Looks like this was added only in Gradle 6.5. Unfortunately your only option is to upgrade to Gradle 6.5 or 7 here. I'll update the README to reflect this.
