### ISSUE TITLE
does this work with android espresso? aka instrumented android tests?

### ISSUE THREAD

**Issue by carlos-vargas-pplus** [radarsh/gradle-test-logger-plugin#268]
**Description**

I need to have a better report tooling on my jenkins console when running android espresso tests. I want to know if this can work for android espresso

**Comment by radarsh** [comment]
Sorry no idea what Android expresso is. Never done any Android app development. What issues are you facing?

**Comment by calvario31** [comment]
hello, android espresso is instrumented test is like appium but from android code https://developer.android.com/training/testing/espresso since we run tests using gradle + android I wanted to know if this is possible to do with espresso

**Comment by radarsh** [comment]
In theory it should be possible as long as you can tests using Gradle.

**Comment by calvarioTeacher31** [comment]
hello im answering from another account. At the end we implement allure reports so didnt need this as reporting tool

**Comment by cdavie-artium** [comment]
Related: https://github.com/radarsh/gradle-test-logger-plugin/issues/111
