### ISSUE TITLE
Print class name in the same line as the test name

### ISSUE THREAD

**Issue by dbardbar** [radarsh/gradle-test-logger-plugin#285]
**Description**

Print class name in the same line as the test name

**Additional information**

Today the output prints the class name (either full or simple name), then the test output stream(s) are printed, and when test finishes the summary of the test is written.
In cases where there's a lot of logs written by a test, it is hard to understand which class the test belongs to.
It would be great to have an option to also print the class name next to the test name. 
I think this should be controlled by a flag orthogonal to the simple/full class name.

Suggested example of output:

TestClass
  Test TestClass::test1() PASSED (3ms)
  Test TestClass::test2() PASSED (5ms)

Or with showSimpleNames = false:

com.company.TestClass
  com.company.Test TestClass::test1() PASSED (3ms)
  com.company.Test TestClass::test2() PASSED (5ms)

**Comment by radarsh** [comment]
This already happens if you use one of the parallel themes. Is this not what you're after?

![image](https://user-images.githubusercontent.com/534512/188448212-09f53deb-31de-4105-8b21-b65a07f0f496.png)
