### ISSUE TITLE
Output to file

### ISSUE THREAD

**Issue by szysas** [radarsh/gradle-test-logger-plugin#300]
**Description**

Possibility to output test logs also to file.

**Additional information**

This plugin produces really good test report, it would be good to utilise it as a report in a file. My use case is to use it in CI, for example in GitHub action to export report into summary: `cat report.txt >> $GITHUB_STEP_SUMMARY`

**Comment by radarsh** [comment]
Gradle already produces reports. Is this something you have already explored and still found the need for the plugin to do the same?

**Comment by szymonsasin-nordic** [comment]
Yes, but those are either xml or html reports, very detailed ones. Output generated by this plugin is more compact and nicer for a 'quick' look. Could not find any other plugin that would generate compact, textual test report.

**Comment by szysas** [comment]
Yes, but those are either xml or html reports, very detailed ones. Output generated by this plugin is more compact and nicer for a 'quick' look. Could not find any other plugin that would generate compact, textual test report.

**Comment by radarsh** [comment]
Let me think about that. It will likely involve coming up with a custom test reporter. Currently the plugin is only a test logger listener which produces output in near real-time.

**Comment by radarsh** [comment]
Suggestion is to continue using the output redirection feature provided by the shell to keep the scope of the plugin focussed.
