### ISSUE TITLE
The `Provider.forUseAtConfigurationTime` method has been deprecated.	

### ISSUE THREAD

**Issue by Goooler** [radarsh/gradle-test-logger-plugin#321]
**Description**

> [Provider#forUseAtConfigurationTime](https://docs.gradle.org/8.3/javadoc/org/gradle/api/provider/Provider.html#forUseAtConfigurationTime--) is now deprecated and scheduled for removal in Gradle 9.0. Clients should simply remove the call.

https://docs.gradle.org/8.3/userguide/upgrading_version_7.html?#for_use_at_configuration_time_deprecation

**Versions**

- Test logger version: 3.2.0
- Gradle version: 8.3
- Java version: 17

**Comment by sildvauresberg** [comment]
I suppose this plugin is no longer maintained and we should either implement similar functionality without any third party plugins or fork this plugin.

**Comment by Goooler** [comment]
I can do this in that case.

**Comment by radarsh** [comment]
Plugin is definitely active. I haven't had the time recently to contribute much due to personal circumstances. 

I will see if I can implement this in the coming days.

**Comment by Goooler** [comment]
Addressing the fix to #322.
