### ISSUE TITLE
Not supporting Configuration Cache in v4.0.0

### ISSUE THREAD

**Issue by ranjeet-porter** [radarsh/gradle-test-logger-plugin#339]
FAILURE: Build failed with an exception.

* What went wrong:
Configuration cache problems found in this build.

75 problems were found storing the configuration cache, 38 of which seem unique.
- Plugin 'com.adarshr.test-logger': read system property 'idea.io.use.nio2'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'sun.jnu.encoding'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'sun.arch.data.model'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'sun.boot.library.path'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'sun.java.command'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'jdk.debug'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'java.vm.compressedOopsMode'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'idea.home.path'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'sun.management.compiler'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'file.encoding'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'psi.incremental.reparse.depth.limit'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'java.io.tmpdir'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'native.encoding'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'sun.io.unicode.encoding'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Plugin 'com.adarshr.test-logger': read system property 'library.jansi.path'
  See https://docs.gradle.org/7.0.2/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
plus 23 more problems. Please see the report for details.

> Listener registration 'Gradle.addListener' by build ' is unsupported.
> Read system property 'idea.io.use.nio2'
> Read system property 'sun.jnu.encoding'
> Read system property 'sun.arch.data.model'
> Read system property 'sun.boot.library.path'

**Comment by radarsh** [comment]
As per the [compatibility matrix](https://github.com/radarsh/gradle-test-logger-plugin?tab=readme-ov-file#compatibility-matrix), you need to be running at minimum Gradle 7.6 to be able to use plugin version 4.x.
