### ISSUE TITLE
Are you planning to support jUnit 5?

### ISSUE THREAD

**Issue by pnowy** [radarsh/gradle-test-logger-plugin#47]
Hi,

the plugin is great but I have a question regarding jUnit 5? Are you planning to support it on the future?

Thanks

**Comment by radarsh** [comment]
Hi, thanks for checking it out. I do have plans to support JUnit 5. Did you face any issues with it?

**Comment by pnowy** [comment]
I've tried it today (Spring Boot 2 RC.1 + jUnit 5.0.3 + some old tests on jUnit 4.12 with vintage engine) but in this case the logs from plugin disappear. Currently I see the Spring logs (you know context setup, etc.) - these information were hidden in 4.12 runner (visible only in -i mode).

**Comment by radarsh** [comment]
OK let me try a similar setup and get back to you.

**Comment by radarsh** [comment]
@pnowy Have you come across Gradle 4.6 with first class support for JUnit 5? I've tried and the plugin works with no issues.

**Comment by pnowy** [comment]
@radarsh could you paste the screenshot? To be honest with Gradle 4.6 and first class JUnit 5 support I didn't notice any difference with or without plugin (for gradle 4.6 there build-in logger with green `PASSES` text for each test)

**Comment by pnowy** [comment]
Ok - I have a different view. I will check tomorrow your feature branch and compare with my project configuration.

**Comment by radarsh** [comment]
@pnowy when you get a chance, can you confirm if it works for you? If not, would appreciate some additional debug info such as the maybe a screenshot of the output you see. Thanks.

**Comment by pnowy** [comment]
Hi, I've checked issue today and it works now! I'm not sure whether you changed anything or my previous configuration was wrong. I'm closing the issue. Thx for help!

**Comment by radarsh** [comment]
I haven't released a new version yet so what you have is the existing code. I will merge the new tests for future reference.

**Comment by pnowy** [comment]
Ok - so that was something on my side. Anyway - works with jUnit 5 👍
