### ISSUE TITLE
add option to display STDOUT

### ISSUE THREAD

**Issue by markhu** [radarsh/gradle-test-logger-plugin#50]
I like this plugin, but only wish it had an option to display the standard output stream.

Granted, I could add the standard Gradle`-i` or `--info` switch, but adds too much extra info. Is there a middle ground?

**Comment by radarsh** [comment]
Thanks for using this plugin. I could add an option to display standard output but that would clutter the currently balanced output. Would you still like it?

**Comment by markhu** [comment]
I would love it. Agree it isn't pretty, but I commonly do `println` temporarily while getting a new project started.

**Comment by radarsh** [comment]
Have tried to make it as pretty as possible without (hopefully) sacrificing readability.

![image](https://user-images.githubusercontent.com/534512/37866234-d5eb5ee2-2f7f-11e8-8ce5-89972b852d7f.png)

**Comment by radarsh** [comment]
@markhu I'm currently encountering some platform-dependent issues. I'm trying to address those but as soon as I do, I will be releasing a new version.

**Comment by radarsh** [comment]
@markhu Released `v1.2.0`. Please test and let me know. Usage is [here](https://github.com/radarsh/gradle-test-logger-plugin#show-standard-streams)
