### ISSUE TITLE
Slow test that failed doesn't show the execution time

### ISSUE THREAD

**Issue by WaaX** [radarsh/gradle-test-logger-plugin#51]
What I expect to see:
  Test thisIsASlowTestThatFailed FAILED (9.2s)

What I see:
  Test thisIsASlowTestThatFailed FAILED

**Comment by radarsh** [comment]
Can I check if you have set any value for `slowThreshold` at all?

**Comment by WaaX** [comment]
I do, I used your exact sample configuration. I do see the execution time for the tests that passed.  

In this screenshot, the failed test took more than 1min to run. The succcessfull one shows the execution time but not he failed test.
![screenshot2018-03-16at11 15 35am](https://user-images.githubusercontent.com/147802/37529542-d206dd24-290d-11e8-80ae-1293c0bf8455.jpg)

**Comment by radarsh** [comment]
OK, thanks for this info @WaaX. I just realised that the display of duration was never implemented for failed and skipped tests. I'll implement this.
