### ISSUE TITLE
Bright yellow is not readable if console has bright background

### ISSUE THREAD

**Issue by eloo** [radarsh/gradle-test-logger-plugin#59]
Hi,
i really like your plugin and the well formatted output but the bright yellow of the test class name is really hard to read on bright backgrounds like jenkins has.
Would it be possible to exchange all bright yellows to another color?

Thanks

**Comment by radarsh** [comment]
Hi @eloo thanks for using the plugin. I too did notice this a few days ago when I enabled colours on Jenkins. Let me think of an alternative colour for Bright Yellow.
