### ISSUE TITLE
Add support for parallel test execution

### ISSUE THREAD

**Issue by radarsh** [radarsh/gradle-test-logger-plugin#8]
Currently if `maxParallelForks` is set to anything other than `1`, the plugin throws an exception. This can be quite limiting.

**Comment by eriwen** [comment]
Thanks for providing a great plugin! I'd like to advocate for this feature, since that makes this plugin useful for a large number of projects. 

If you let us (Gradle team) know what you're struggling with (maybe on [the forums](https://discuss.gradle.org)), we may have a good answer for you. Thanks again.

**Comment by radarsh** [comment]
Thanks for the feedback. The main challenge I’m facing is being able to group tests by suites when they are executed in parallel. So by ensuring that there is only one parallel fork (Gradle default) I can achieve the grouping. 

I will soon post on the forum too with more details.

**Comment by radarsh** [comment]
@eriwen I've [explained in detail](https://discuss.gradle.org/t/parallel-test-execution-support-for-gradle-test-logger-plugin/24977) on the forums.

**Comment by pivotal-jbarrett** [comment]
@radarsh I'd really like to use this plugin to get some better logging of progress in our builds when console is in `plain` mode (our CI chokes on Gradle's `rich` output). The problem I have is I need this `maxParallelForks` issue to work. Looking at your discussion on the forum linked above either solution would be sufficient for me to take this into production. If I was to simply fork you plugin and remove that assertion would I end up with the odd groupings at least? If so would you consider this as a sufficient step forward to just include it in your releases? I feel like something is better than nothing at this point.

**Comment by radarsh** [comment]
@pivotal-jbarrett let me see what I can do. This issue has been open for far too long.

**Comment by radarsh** [comment]
I have a working prototype using the [second approach](https://discuss.gradle.org/t/parallel-test-execution-support-for-gradle-test-logger-plugin/24977) I have described on the forum before. Screenshots:

#### Plain (parallel) theme:
![image](https://user-images.githubusercontent.com/534512/43185300-67f2a7f0-8fe3-11e8-99f6-06640ea5fa6f.png)
#### Standard (parallel) theme:
![image](https://user-images.githubusercontent.com/534512/43185317-76555f4a-8fe3-11e8-9ad9-4500837e7d21.png)
#### Mocha (parallel) theme:
![image](https://user-images.githubusercontent.com/534512/43185331-7ea8cd44-8fe3-11e8-868e-21e18f7c4d33.png)
 
Will work on getting this ready for the next release of the plugin.
