### ISSUE TITLE
Use of testLogger.showStandardStreams can lead to confusion

### ISSUE THREAD

**Issue by ivoanjo** [radarsh/gradle-test-logger-plugin#86]
Hello there,

Thank you very much for this nice plugin! We really need user-friendly tools like yours in the Java community!

I was looking for a way to enable printing of stdout/stderr of my tests, and everywhere I googled I was pointed at [gradle Test task's `testLogging.showStandardStreams` option](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html).

But because I use `gradle-test-logger-plugin`, this wasn't working. After some time it dawned on me that the issue may come from the plugin, and I was able to confirm this and then go into the documentation and see that with this plugin, one should actually use `testLogger.showStandardStreams` instead.

Since this is a bit confusing, I would like to suggest that support for reading from `testLogging.showStandardStreams` also be added. I believe that would a lot more predictable for people with existing test configurations, and hopefully no other users would lose a few minutes banging their heads against this small issue.

Thanks for your time! :pray:

**Comment by radarsh** [comment]
This is a great idea, thanks for the feedback. 

I'll see if I can derive any other values based on the configuration of `testLogging`.

**Comment by radarsh** [comment]
This is dependent on #90 as `testLogging.showStandardStreams` can be virtually configured for any task of type `Test` and it wouldn't be right to change the global testlogger configuration based on the value of any individual test task configuration.

**Comment by ivoanjo** [comment]
Thank you for the awesome fix! :+1:
