### ISSUE TITLE
JUnit5 Gradle Plugin interferes with this one

### ISSUE THREAD

**Issue by gajwani** [radarsh/gradle-test-logger-plugin#87]
Hi! 

Here's our story: a teammate and I were trying to get your plugin working on our project. It took us a good amount of time, but we figured out why it wasn't working: the `junit-platform-gradle-plugin` was preventing most of the output from this plugin. 

While there is a [small blurb](https://junit.org/junit5/docs/current/user-guide/#running-tests-build-gradle) in the documentation about that plugin being deprecated, we still had it in our `build.gradle` because, I think, of some copy-pasta from older JUnit5 documentation.

It may be worth adding a note to your README that this might cause problems.

Regardless, this plugin works great! Thanks for the work you put in to it.

**Comment by radarsh** [comment]
Thanks for this feedback. Will update the FAQ.

**Comment by gajwani** [comment]
Thanks!

**Comment by gajwani** [comment]
Haha, sorry, I just assumed it could be closed. Thanks again for incorporating the feedback!
