### ISSUE TITLE
A couple usability suggestions

### ISSUE THREAD

**Issue by cjstehno** [radarsh/gradle-test-logger-plugin#88]
I like the plugin but I ran into a couple things that would be nice to have (especially during first-time use):

1. Small but took a minute to find - I am used to camelCase with Java and Groovy names, so I started out with `testLogger` eventually realized the `L` is not capitalized. Maybe make both valid or just point out the difference in the documentation.
2. My projects use parallel tests which caused the theme to fail. It appears to know that I am using parallel testing - if this is the case, could you not switch to the parallel version of the same theme and provide a warning log that this change was made.

These are just suggestions - feel free to close this issue if they are not something you want to pursue.

**Comment by radarsh** [comment]
I would like the plugin's behaviour to be predictable. Therefore, I am going to abandon the idea of automatically switching themes based on Gradle settings, at least for now.
