### ISSUE TITLE
Print list of tests before execution

### ISSUE THREAD

**Issue by dlapunas** [radarsh/gradle-test-logger-plugin#91]
Not sure if this is possible with JUnit, but I'd like to see the list of tests before they're run. I have some long test suites and knowing that the tests I want to execute will be executed is very much useful to me.

**Comment by radarsh** [comment]
I think it's unlikely that Gradle has this capability. It's all event driven and this plugin just registers itself as a listener of those events. But let me check to be sure.

**Comment by radarsh** [comment]
Unfortunately there's nothing this plugin can do about this as Gradle doesn't yet have an option to list the tests before actually running them. Also see gradle/gradle#2129
