### ISSUE TITLE
Doesn't render tickmarks for mocha theme on Windows

### ISSUE THREAD

**Issue by TAGC** [radarsh/gradle-test-logger-plugin#99]
The tickmarks from the "mocha" and "mocha-parallel" theme get rendered as question marks on Windows, as shown below.

![mintty_2018-10-31_08-49-29](https://user-images.githubusercontent.com/1588951/47776435-4e5d5e80-dcea-11e8-9678-7eeaa68e799d.png)

Tested on:
 - Git Bash (through Mintty 2.8.5)
 - Cygwin (through Mintty 2.9.0)
 - cmd

I'm using 64-bit Windows 10.

**Comment by radarsh** [comment]
Hi @TAGC, have you tried [doing this from the FAQs](https://github.com/radarsh/gradle-test-logger-plugin#does-it-work-on-windows)?

**Comment by TAGC** [comment]
That's probably it. I'm having trouble changing the encoding used during testing, though. In your `build.gradle` script you set it via the `systemProperty` method for your test task:

https://github.com/radarsh/gradle-test-logger-plugin/blob/328bdfa9d3a3969262fd4e0f769a920450f4de88/build.gradle#L75-L85

I'm using the Kotlin DSL and tried doing the equivalent in mine:

```kotlin
val test by tasks.getting(Test::class) {
    useJUnitPlatform { }

    systemProperties["file.encoding"] = "UTF-8"
    systemProperties["foo"] = "bar"
    println(systemProperties)

    testLogging {
        events("PASSED", "FAILED", "SKIPPED")
    }

    testlogger {
        setTheme("mocha")
    }
}
```

The "foo" property gets set but the file encoding still remains as windows-1252:

![mintty_2018-10-31_09-32-32](https://user-images.githubusercontent.com/1588951/47778985-f6c1f180-dcef-11e8-921b-a375d8c63d2e.png)

But yeah if I fix that, I guess that'll resolve this issue.

**Comment by TAGC** [comment]
Creating a `gradle.properties` file in my root project directory containing `org.gradle.jvmargs='-Dfile.encoding=UTF-8'` causes the Gradle test task to use UTF-8 file encoding (I see `-Dfile.encoding=UTF-8` instead of `-Dfile.encoding=windows-1252` now).

I still see question marks, but I guess the next step is to change the terminal code page as shown in the FAQ. I'll update when I've tried that.

**Comment by radarsh** [comment]
Is it not `systemProperty "foo", "bar"` in Kotlin DSL? Just guessing as I'm not familiar with Kotlin DSL syntax.

> I still see question marks, but I guess the next step is to change the terminal code page as shown in the FAQ. I'll update when I've tried that.

Unfortunate truth about Windows :-(

**Comment by TAGC** [comment]
I checked - my charset is already 65001 and it doesn't work:

![powershell_2018-10-31_09-55-24](https://user-images.githubusercontent.com/1588951/47780495-67b6d880-dcf3-11e8-8314-0ec975295a71.png)

Are you sure it's not just a problem with the way your library tries to render it? I've got a JS project and I can see the tickmarks render fine in PowerShell when I run the tests in that:

![powershell_2018-10-31_10-22-46](https://user-images.githubusercontent.com/1588951/47782005-11e42f80-dcf7-11e8-80f9-493c270f12fb.png)

**Comment by radarsh** [comment]
I have done a similar comparison in the past and isolated the problem to the way Java prints Strings on the console. The JS libraries on the other hand, ultimately delegate to native code to do the printing. 

But I have it working on my Windows machine. Let me share some settings in sometime.

By the way you can try cloning this repo and running the tests to see if it's a problem with the plugin code or some configuration in your project.

`./gradlew test` should print the results using the mocha theme.

**Comment by TAGC** [comment]
I tried it, I see this:

![mintty_2018-10-31_10-41-15](https://user-images.githubusercontent.com/1588951/47783014-9041d100-dcf9-11e8-8535-30ab16803ed5.png)

**Comment by radarsh** [comment]
I had to set `JAVA_OPTS` at shell level. Just realised that's what the FAQ says, although not very explicit. See below, let me know if it helps:

```
PS C:\Development\workspace\gradle-test-logger-plugin> ./gradlew test --tests "*does not log*"

> Task :test

  com.adarshr.gradle.testlogger.logger.ConsoleLoggerSpec

    ? does not log empty strings

  1 passing (3.6s)


BUILD SUCCESSFUL in 9s
7 actionable tasks: 1 executed, 6 up-to-date
PS C:\Development\workspace\gradle-test-logger-plugin> $Env:JAVA_OPTS = "-Dfile.encoding=UTF-8"
PS C:\Development\workspace\gradle-test-logger-plugin> chcp 65001
Active code page: 65001
PS C:\Development\workspace\gradle-test-logger-plugin> ./gradlew clean test --tests "*does not log*"

> Task :test

  com.adarshr.gradle.testlogger.logger.ConsoleLoggerSpec

    √ does not log empty strings

  1 passing (2.8s)


BUILD SUCCESSFUL in 12s
8 actionable tasks: 8 executed
```

**Comment by TAGC** [comment]
Ah okay, yeah that works, thanks. Shame that it has to be done through the environment variable though and doesn't pick up on the equivalent setting defined in `gradle.properties`.
